services:
  tweedegolf_swiftmailer_logger.send_listener:
    class: TweedeGolf\SwiftmailerLoggerBundle\EventListener\SendListener

  # loggers
  tweedegolf_swiftmailer_logger.entity_logger:
    class:  TweedeGolf\SwiftmailerLoggerBundle\Logger\EntityLogger
    arguments:
      - "@doctrine"
      - "@logger"

  tweedegolf_swiftmailer_logger.symfony_logger:
    class:  TweedeGolf\SwiftmailerLoggerBundle\Logger\SymfonyLogger
    arguments:
      - "@logger"

  # todo add a file logger

